=== cs4ec/CS4EC_DSL/solutions/EDRuntime_RepastMainProvider/lib/plugins/repast.simphony.batch_2.7.0/models/batch_params.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sweep">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="sweep" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="runs" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parameter" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="constant_type" type="xs:string"/>
      <xs:attribute name="value" type="xs:string"/>
      <xs:attribute name="start" type="xs:string"/>
      <xs:attribute name="end" type="xs:string"/>
      <xs:attribute name="step" type="xs:string"/>
      <xs:attribute name="value_type" type="xs:string"/>
      <xs:attribute name="values" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cs4ec/CS4EC_DSL/jars/plugins/repast.simphony.batch_2.7.0/models/test_batch_params2.xml
<?xml version="1.0"?>
<sweep runs="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="batch_params.xsd">

  <parameter name="double_const" type="constant" constant_type="number" value="4.0"/>
  <parameter name="long_const" type="constant" constant_type="number" value="11L"/>
	<parameter name="string_const" type="constant" constant_type="string" value="hello cormac"/>
	<parameter name="boolean_const" type="constant" constant_type="boolean" value="false"/>

	<parameter name="long_param" type="number" start="1L" end="3" step="1">
		<parameter name="float_param" type="number" start=".8f" end="1.0f" step=".1f">
			<parameter name="string_param" type="list" value_type="String" values="foo bar">
				<parameter name="randomSeed" type="list" value_type="int" values="1 2"/>
				</parameter>
		</parameter>
	</parameter>
</sweep>
